DbExchangeSystem/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from account.views import submitRequestPage, loginPage, registerPage, logoutUser, itemRequestSearch, itemRequestViewPage, deleteItem, load_subcategories, organizationPage, itemRequestPage, discoverPage, profilePage, homePage, sendEmail, organizationSearch, submitItemPage, itemPage, itemViewPage, deleteItem2, sendEmail2, itemSearch, discoverPage2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', loginPage, name="login"),
    path('register/', registerPage, name="register"),
    path('search_item_requests/', itemRequestSearch, name="display"),
    path('logout/', logoutUser, name="logout"),
    path('submitItemRequest/', submitRequestPage, name="submit"),
    path('view_items_requests/', itemRequestViewPage, name="viewitemrequests"),
    path('delete_item/<str:pk>/', deleteItem, name="deleteitem"),
    path('ajax/load-subcategories/', load_subcategories, name="ajax_load_subcategories"),
    path('organization_details/<str:pk>', organizationPage, name="organizationPage"),
    path('item_request_details/<str:pk>', itemRequestPage, name="itemRequestPage"),
    path('discoverItemRequests/', discoverPage, name="discoverPage"),
    path('discoverItemsAvailable/', discoverPage2, name="discoverPage2"),
    path('profile/', profilePage, name="profilePage"),
    path('home/', homePage, name="homePage"),
    path('email/<str:pk>/<str:pk2>', sendEmail, name="sendEmail"),
    path('search_organizations', organizationSearch, name="organizationSearch"),
    path('submitItem/', submitItemPage, name="submitItemPage"),
    path('item_details/<str:pk>', itemPage, name="itemPage"),
    path('view_items/', itemViewPage, name="itemViewPage"),
    path('delete2/<str:pk>', deleteItem2, name="deleteItem2"),
    path('email2/<str:pk>/<str:pk2>', sendEmail2, name="sendEmail2"),
    path('search_items/', itemSearch, name="itemSearch")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model
)
from account.models import item_request, subcategory, category, item_available
from phone_field import PhoneField
import pgeocode
import math
User = get_user_model()


class UserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError('User does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect Password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegistrationForm(forms.ModelForm):
    email = forms.EmailField(label='Email Address', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    organization_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    organization_website = forms.URLField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    organization_description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    admin_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    postal_code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = [
            'email', 'password', 'organization_name', 'organization_website', 'organization_description', 'admin_name', 'phone_number', 'country', 'postal_code', 'logo'
        ]

    def clean_email(self):
        email = self.cleaned_data.get('email')
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError(
                "This email is already being used"
            )
        return email

    def clean_organization_website(self):
        organization_website = self.cleaned_data.get('organization_website')
        website_qs = User.objects.filter(organization_website=organization_website)
        if website_qs.exists():
            raise forms.ValidationError(
                "This website URL is already being used"
            )
        return organization_website

    def clean_organization(self):
        cd = self.cleaned_data
        organization_name = cd.get('organization_name')
        organization_name_qs = User.objects.filter(organization_name=organization_name)
        if organization_name_qs.exists():
            raise forms.ValidationError(
                "This organization name is already being used"
            )
        return cd.get('organization')

    def clean_country(self):
        cd = self.cleaned_data
        try:
            nomi = pgeocode.Nominatim(cd.get('country'))
        except:
            raise forms.ValidationError("Your country is not supported currently")
        return cd.get('country')

    def clean_postal_code(self):
        cd = self.cleaned_data
        try:
            nomi = pgeocode.Nominatim(cd.get('country'))
            if (str(nomi.query_postal_code(cd.get('postal_code')).loc["country code"]) != str (cd.get('country'))):
                raise forms.ValidationError("Your postal code is invalid")
        except:
            raise forms.ValidationError("Your postal code is invalid")
        return cd.get('postal_code')

class ItemForm(forms.ModelForm):
    item_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_quantity = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = item_available
        exclude = ('item_organization',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['item_subcategory'].queryset = subcategory.objects.none()

        if 'item_category' in self.data:
            try:
                category_id = int(self.data.get('item_category'))
                self.fields['item_subcategory'].queryset = subcategory.objects.filter(category_id=category_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['item_subcategory'].queryset = self.instance.item_category.item_subcategory_set

class ItemRequestForm(forms.ModelForm):
    item_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_reason = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_quantity = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_start_date = forms.DateField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_end_date = forms.DateField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = item_request
        exclude = ('item_organization',)

    def clean(self):
        cd = self.cleaned_data
        start = cd.get("item_start_date")
        end = cd.get("item_end_date")
        if end < start:
            raise forms.ValidationError("End date should be greater than or equal to start date")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['item_subcategory'].queryset = subcategory.objects.none()

        if 'item_category' in self.data:
            try:
                category_id = int(self.data.get('item_category'))
                self.fields['item_subcategory'].queryset = subcategory.objects.filter(category_id=category_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['item_subcategory'].queryset = self.instance.item_category.item_subcategory_set

class organizationSearchForm(forms.Form):
    DISTANCE_CHOICES = [
        ('anywhere', 'Anywhere'),
        ('country', 'Within My Country'),
        ('100', "Within 100 km"),
        ('50', "Within 50 km"),
        ('25', "Within 25 km"),
        ('10', "Within 10km"),
        ('postalcode', "Within my postal code")
    ]
    organization_name = forms.CharField(label="Organization Name", max_length=100, required=False)
    organization_distance = forms.CharField(widget=forms.Select(choices=DISTANCE_CHOICES))

class searchForm2(forms.Form):
    DISTANCE_CHOICES = [
        ('anywhere', 'Anywhere'),
        ('country', 'Within My Country'),
        ('100', "Within 100 km"),
        ('50', "Within 50 km"),
        ('25', "Within 25 km"),
        ('10', "Within 10km"),
        ('postalcode', "Within my postal code")
    ]
    item_request_name = forms.CharField(label="Item Name", max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_organization_name = forms.CharField(label="Organization Name", max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_distance = forms.CharField(widget=forms.Select(choices=DISTANCE_CHOICES))
    item_category = forms.ModelChoiceField(queryset=category.objects.all(), required=False)
    item_subcategory = forms.ModelChoiceField(queryset=subcategory.objects.all(), required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['item_subcategory'].queryset = subcategory.objects.none()

        if 'item_category' in self.data:
            try:
                category_id = int(self.data.get('item_category'))
                self.fields['item_subcategory'].queryset = subcategory.objects.filter(category_id=category_id)
            except (ValueError, TypeError):
                pass

class searchForm(forms.Form):
    DISTANCE_CHOICES = [
        ('anywhere', 'Anywhere'),
        ('country', 'Within My Country'),
        ('100', "Within 100 km"),
        ('50', "Within 50 km"),
        ('25', "Within 25 km"),
        ('10', "Within 10km"),
        ('postalcode', "Within my postal code")
    ]
    item_request_name = forms.CharField(label="Item Name", max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_organization_name = forms.CharField(label="Organization Name", max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_start_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_end_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    item_distance = forms.CharField(widget=forms.Select(choices=DISTANCE_CHOICES))
    item_category = forms.ModelChoiceField(queryset=category.objects.all(), required=False)
    item_subcategory = forms.ModelChoiceField(queryset=subcategory.objects.all(), required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['item_subcategory'].queryset = subcategory.objects.none()

        if 'item_category' in self.data:
            try:
                category_id = int(self.data.get('item_category'))
                self.fields['item_subcategory'].queryset = subcategory.objects.filter(category_id=category_id)
            except (ValueError, TypeError):
                pass

class emailForm(forms.Form):

templates/delete.html
{% extends 'basic.html' %}
{% block title %} Delete Item {% endblock %}
{% load static %}
{% block css %}
    .login {
        text-align:center;
    }
    .container {
        width:25%;
    }
    .form-group {
        font-family:Palatino;
    }
{% endblock %}
{% block body %}
<div class="container">
    <div class="login">
    <div class="form-group">
        <br>
        <br>
    <p1>Are you sure you want to delete "{{ item }}?"</p1>
        <br>
<form action="{% url 'deleteitem' item.id %}" method = "POST">
    {% csrf_token %}
    <a href="{% url 'viewitemrequests' %}">Cancel</a>

        <button class="btn btn-secondary">Delete</button>
</form>
    </div>
    </div>
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
{% endblock %}

templates/delete2.html
{% extends 'basic.html' %}
{% block title %} Delete Item {% endblock %}
{% load static %}
{% block css %}
    .login {
        text-align:center;
    }
    .container {
        width:25%;
    }
    .form-group {
        font-family:Palatino;
    }
{% endblock %}
{% block body %}
<div class="container">
    <div class="login">
    <div class="form-group">
        <br>
        <br>
    <p1>Are you sure you want to delete "{{ item }}?"</p1>
        <br>
<form action="{% url 'deleteItem2' item.id %}" method = "POST">
    {% csrf_token %}
    <a href="{% url 'itemViewPage' %}">Cancel</a>

        <button class="btn btn-secondary">Delete</button>
</form>
    </div>
    </div>
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
{% endblock %}

templates/item_search.html
{% extends 'basic.html' %}
{% block title %} Search Items {% endblock %}
{% load static %}
{% block css %}
    .login {
        text-align:center;
    }
    .container {
        width:25%;
    }
    .form-group {
        font-family:Palatino;
    }
    $baseColor: #398B93;
$borderRadius: 10px;
$imageBig: 100px;
$imageSmall: 60px;
$padding: 10px;

body {
   background-color: lighten($baseColor, 30%);
   * { box-sizing: border-box; }
}

.header {
   background-color: darken($baseColor, 5%);
   color: white;
   font-size: 1.5em;
   padding: 1rem;
   text-align: center;
   text-transform: uppercase;
}

img {
   height: $imageSmall;
   width: $imageSmall;
}

.table-users {
   border: 1px solid darken($baseColor, 5%);
   border-radius: $borderRadius;
   box-shadow: 3px 3px 0 rgba(0,0,0,0.1);
   max-width: calc(100% - 2em);
   margin: 1em auto;
   overflow: hidden;
   width: 800px;
}

table {
   width: 100%;

   td, th {
      color: darken($baseColor, 10%);
      padding: $padding;
   }

   td {
      text-align: center;
      vertical-align: middle;

      &:last-child {
         font-size: 0.95em;
         line-height: 1.4;
         text-align: left;
      }
   }

   th {
      background-color: lighten($baseColor, 50%);
      font-weight: 300;
   }

   tr {
      &:nth-child(2n) { background-color: white; }
      &:nth-child(2n+1) { background-color: lighten($baseColor, 55%) }
   }
}

@media screen and (max-width: 700px) {
   table, tr, td { display: block; }

   td {
      &:first-child {
         position: absolute;
         top: 50%;
         transform: translateY(-50%);
         width: $imageBig;
      }

      &:not(:first-child) {
         clear: both;
         margin-left: $imageBig;
         padding: 4px 20px 4px 90px;
         position: relative;
         text-align: left;

         &:before {
            color: lighten($baseColor, 30%);
            content: '';
            display: block;
            left: 0;
            position: absolute;
         }
      }

      &:nth-child(2):before { content: 'Name:'; }
      &:nth-child(3):before { content: 'Email:'; }
      &:nth-child(4):before { content: 'Phone:'; }
      &:nth-child(5):before { content: 'Comments:'; }
   }

   tr {
      padding: $padding 0;
      position: relative;
      &:first-child { display: none; }
   }
}

@media screen and (max-width: 500px) {
   .header {
      background-color: transparent;
      color: lighten($baseColor, 60%);
      font-size: 2em;
      font-weight: 700;
      padding: 0;
      text-shadow: 2px 2px 0 rgba(0,0,0,0.1);
   }

   img {
      border: 3px solid;
      border-color: lighten($baseColor, 50%);
      height: $imageBig;
      margin: 0.5rem 0;
      width: $imageBig;
   }

   td {
      &:first-child {
         background-color: lighten($baseColor, 45%);
         border-bottom: 1px solid lighten($baseColor, 30%);
         border-radius: $borderRadius $borderRadius 0 0;
         position: relative;
         top: 0;
         transform: translateY(0);
         width: 100%;
      }

      &:not(:first-child) {
         margin: 0;
         padding: 5px 1em;
         width: 100%;

         &:before {
            font-size: .8em;
            padding-top: 0.3em;
            position: relative;
         }
      }

      &:last-child  { padding-bottom: 1rem !important; }
   }

   tr {
      background-color: white !important;
      border: 1px solid lighten($baseColor, 20%);
      border-radius: $borderRadius;
      box-shadow: 2px 2px 0 rgba(0,0,0,0.1);
      margin: 0.5rem 0;
      padding: 0;
   }

   .table-users {
      border: none;
      box-shadow: none;
      overflow: visible;
   }
}
{% endblock %}
{% block body %}
    <div class="container">
    <div class="login">
    <div class="form-group">
        <br>
        <br>
    <h1>Search Items</h1>
        <br>
    <form method ="POST" id="search_item" data-subcategorys-url="{% url 'ajax_load_subcategories' %}" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {{ searchform.as_p }}
        <button class="btn btn-secondary">Search</button>
    </form>
    </div>
    </div>
    </div>

    <div class="table-users">
   <div class="header">Users</div>

   <table cellspacing="0">
      <tr>
         <th>Image</th>
         <th>Item Name</th>
         <th>Organization</th>
         <th>Details</th>
      </tr>
       {% for item in queryset %}
      <tr>
         <td><img src="{{ item.item_image.url }}" alt = "Image of {{ item.image_name }}" style ="max-height:100px;max-width:100px"></td>
         <td>{{ item.item_name }}</td>
         <td><a href="{% url 'organizationPage' item.item_organization.id%}">{{ item.item_organization }}</a></td>
         <td><a href="{% url 'itemPage' item.id%}">View Details</a></td>
      </tr>
        {% endfor %}
   </table>
    </div>
{#    <ul style="list-style:none">#}
{#        {% for item in queryset %}#}
{#            <li>#}
{#                <img src="{{ item.item_image.url }}" alt = "Image of {{ item.item_name }}" style ="max-height:100px;max-width:100px">#}
{#                <span>Item name: {{ item.item_name }}</span>#}
{#                <span>Organization: <a href="{% url 'organizationPage' item.item_organization.id%}">{{ item.item_organization }}</a></span>#}
{#                 <span><a href="{% url 'itemPage' item.id%}">View Details</a></span>#}
{#                <hr>#}
{#            </li>#}
{#        {% endfor %}#}
{#    </ul>#}
    <!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_item_category").change(function() {
            var url = $("#search_item").attr("data-subcategorys-url");
            var categoryId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'item_category': categoryId
                },
                success: function (data) {
                    $("#id_item_subcategory").html(data);
                }
            });
        });
    </script>
{% endblock %}

templates/login.html
{% extends 'basic.html' %}
{% block title %} Login {% endblock %}
{% load static %}
{% block css %}
    .login {
        text-align:center;
    }
    .container {
        width:25%;
    }
    .form-group {
        font-family:Palatino;
    }
{% endblock %}
{% block body %}
    <div class="container">
    <div class="login">
    <div class="form-group">
        <br>
        <br>
    <h1>Login</h1>
        <br>
    <form method ="POST">
        {% csrf_token %}
        {{form.as_p}}
        <br>
        <button class="btn btn-secondary">Login</button>
    </form>
        <br>
    <form action="{% url 'register' %}">
        <button class="btn btn-secondary">Register</button>
    </form>
    </div>
    </div>
    </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock %}

templates/submitItemPage.html
{% extends 'basic.html' %}
{% block title %} New Request {% endblock %}
{% load static %}
{% block css %}
    .login {
        text-align:center;
    }
    .container {
        width:25%;
    }
    .form-group {
        font-family:Palatino;
    }
{% endblock %}
{% block body %}
    <div class="container">
    <div class="login">
    <div class="form-group">
        <br>
        <br>
    <h1>New Item</h1>
        <br>
    <form method ="POST" id="item_form" data-subcategorys-url="{% url 'ajax_load_subcategories' %}" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-secondary">Add Item</button>
    </form>
    </div>
    </div>
    </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

{% endblock %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script>
        $("#id_item_category").change(function() {
            var url = $("#item_form").attr("data-subcategorys-url");
            var categoryId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'item_category': categoryId
                },
                success: function (data) {
                    $("#id_item_subcategory").html(data);
                }
            });
        });
        </script>
{% endblock %}

templates/submitRequestPage.html
{% extends 'basic.html' %}
{% block title %} New Request {% endblock %}
{% load static %}
{% block css %}
    .login {
        text-align:center;
    }
    .container {
        width:25%;
    }
    .form-group {
        font-family:Palatino;
    }
{% endblock %}
{% block body %}
    <div class="container">
    <div class="login">
    <div class="form-group">
        <br>
        <br>
    <h1>New Item Request</h1>
        <br>
    <form method ="POST" id="item_request_form" data-subcategorys-url="{% url 'ajax_load_subcategories' %}" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-secondary">Add Item Request</button>
    </form>

    </div>
    </div>
    </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

{% endblock %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script>
        $("#id_item_category").change(function() {
            var url = $("#item_request_form").attr("data-subcategorys-url");
            var categoryId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'item_category': categoryId
                },
                success: function (data) {
                    $("#id_item_subcategory").html(data);
                }
            });
        });
        </script>
{% endblock %}